######################################################################
# Automatically generated by qmake (2.01a) lun. mai 9 08:51:49 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . core
INCLUDEPATH += . ..
DESTDIR = ../bin
OBJECTS_DIR = build
LIBS += ../build/tile.o

# Input
HEADERS += tests_utils.h
SOURCES += tests_main.cpp

HEADERS += core/tests_tile.h
SOURCES += core/tests_tile.cpp
